#include "opcodeTable.h"

OpcodeTable::OpcodeTable() {
    mOpcodeToMnemonicList = {
            {0x00, MnemonicData{"BRK", AddressingMode::IMP}},
            {0x18, MnemonicData{"CLC", AddressingMode::IMP}},
            {0xD8, MnemonicData{"CLD", AddressingMode::IMP}},
            {0x58, MnemonicData{"CLI", AddressingMode::IMP}},
            {0xB8, MnemonicData{"CLV", AddressingMode::IMP}},
            {0xCA, MnemonicData{"DEX", AddressingMode::IMP}},
            {0x88, MnemonicData{"DEY", AddressingMode::IMP}},
            {0xE8, MnemonicData{"INX", AddressingMode::IMP}},
            {0xC8, MnemonicData{"INY", AddressingMode::IMP}},
            {0xEA, MnemonicData{"NOP", AddressingMode::IMP}},
            {0x48, MnemonicData{"PHA", AddressingMode::IMP}},
            {0x08, MnemonicData{"PHP", AddressingMode::IMP}},
            {0x68, MnemonicData{"PLA", AddressingMode::IMP}},
            {0x28, MnemonicData{"PLP", AddressingMode::IMP}},
            {0x40, MnemonicData{"RTI", AddressingMode::IMP}},
            {0x60, MnemonicData{"RTS", AddressingMode::IMP}},
            {0x38, MnemonicData{"SEC", AddressingMode::IMP}},
            {0xF8, MnemonicData{"SED", AddressingMode::IMP}},
            {0x78, MnemonicData{"SEI", AddressingMode::IMP}},
            {0xAA, MnemonicData{"TAX", AddressingMode::IMP}},
            {0xA8, MnemonicData{"TAY", AddressingMode::IMP}},
            {0xBA, MnemonicData{"TSX", AddressingMode::IMP}},
            {0x8A, MnemonicData{"TXA", AddressingMode::IMP}},
            {0x9A, MnemonicData{"TXS", AddressingMode::IMP}},
            {0x98, MnemonicData{"TYA", AddressingMode::IMP}},
            {0xEA, MnemonicData{"NOP", AddressingMode::IMP}},
            {0xA9, MnemonicData{"LDA #${}", AddressingMode::IMM, 1}},
            {0xAD, MnemonicData{"LDA ${}", AddressingMode::ABS, 2}},
            {0xBD, MnemonicData{"LDA ${},X", AddressingMode::X_IN_ABS, 2}},
            {0xB9, MnemonicData{"LDA ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0xA5, MnemonicData{"LDA ${}", AddressingMode::ZP, 1}},
            {0xB5, MnemonicData{"LDA ${},X", AddressingMode::X_IN_ZP, 1}},
            {0xA1, MnemonicData{"LDA (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0xB1, MnemonicData{"LDA (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0xA2, MnemonicData{"LDX #${}", AddressingMode::IMM, 1}},
            {0xAE, MnemonicData{"LDX ${}", AddressingMode::ABS, 2}},
            {0xBE, MnemonicData{"LDX ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0xA6, MnemonicData{"LDX ${}", AddressingMode::ZP, 1}},
            {0xB6, MnemonicData{"LDX ${},X", AddressingMode::Y_IN_ZP, 1}},
            {0xA0, MnemonicData{"LDY #${}", AddressingMode::IMM, 1}},
            {0xAC, MnemonicData{"LDY ${}", AddressingMode::ABS, 2}},
            {0xBC, MnemonicData{"LDY ${},Y", AddressingMode::X_IN_ABS, 2}},
            {0xA4, MnemonicData{"LDY ${}", AddressingMode::ZP, 1}},
            {0xB4, MnemonicData{"LDY ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x8D, MnemonicData{"STA ${}", AddressingMode::ABS, 2}},
            {0x9D, MnemonicData{"STA ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x99, MnemonicData{"STA ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0x85, MnemonicData{"STA ${}", AddressingMode::ZP, 1}},
            {0x95, MnemonicData{"STA ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x81, MnemonicData{"STA (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0x91, MnemonicData{"STA (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0x8E, MnemonicData{"STX ${}", AddressingMode::ABS, 2}},
            {0x86, MnemonicData{"STX ${}", AddressingMode::ZP, 1}},
            {0x96, MnemonicData{"STX ${},X", AddressingMode::Y_IN_ZP, 1}},
            {0x8C, MnemonicData{"STY ${}", AddressingMode::ABS, 2}},
            {0x84, MnemonicData{"STY ${}", AddressingMode::ZP, 1}},
            {0x94, MnemonicData{"STY ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x0A, MnemonicData{"ASL A", AddressingMode::ACC}},
            {0x0E, MnemonicData{"ASL ${}", AddressingMode::ABS, 2}},
            {0x1E, MnemonicData{"ASL ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x06, MnemonicData{"ASL ${}", AddressingMode::ZP, 1}},
            {0x16, MnemonicData{"ASL ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x4A, MnemonicData{"LSR A", AddressingMode::ACC}},
            {0x4E, MnemonicData{"LSR ${}", AddressingMode::ABS, 2}},
            {0x5E, MnemonicData{"LSR ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x46, MnemonicData{"LSR ${}", AddressingMode::ZP, 1}},
            {0x56, MnemonicData{"LSR ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x2A, MnemonicData{"ROL A", AddressingMode::ACC}},
            {0x2E, MnemonicData{"ROL ${}", AddressingMode::ABS, 2}},
            {0x3E, MnemonicData{"ROL ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x26, MnemonicData{"ROL ${}", AddressingMode::ZP, 1}},
            {0x36, MnemonicData{"ROL ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x6A, MnemonicData{"ROR A", AddressingMode::ACC}},
            {0x6E, MnemonicData{"ROR ${}", AddressingMode::ABS, 2}},
            {0x7E, MnemonicData{"ROR ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x66, MnemonicData{"ROR ${}", AddressingMode::ZP, 1}},
            {0x76, MnemonicData{"ROR ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x29, MnemonicData{"AND #${}", AddressingMode::IMM, 1}},
            {0x2D, MnemonicData{"AND ${}", AddressingMode::ABS, 2}},
            {0x3D, MnemonicData{"AND ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x39, MnemonicData{"AND ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0x25, MnemonicData{"AND ${}", AddressingMode::ZP, 1}},
            {0x35, MnemonicData{"AND ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x21, MnemonicData{"AND (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0x31, MnemonicData{"AND (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0x2C, MnemonicData{"BIT ${}", AddressingMode::ABS, 2}},
            {0x24, MnemonicData{"BIT ${}", AddressingMode::ZP, 1}},
            {0x49, MnemonicData{"EOR #${}", AddressingMode::IMM, 1}},
            {0x4D, MnemonicData{"EOR ${}", AddressingMode::ABS, 2}},
            {0x5D, MnemonicData{"EOR ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x59, MnemonicData{"EOR ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0x45, MnemonicData{"EOR ${}", AddressingMode::ZP, 1}},
            {0x55, MnemonicData{"EOR ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x41, MnemonicData{"EOR (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0x51, MnemonicData{"EOR (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0x09, MnemonicData{"ORA #${}", AddressingMode::IMM, 1}},
            {0x0D, MnemonicData{"ORA ${}", AddressingMode::ABS, 2}},
            {0x1D, MnemonicData{"ORA ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x19, MnemonicData{"ORA ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0x05, MnemonicData{"ORA ${}", AddressingMode::ZP, 1}},
            {0x15, MnemonicData{"ORA ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x01, MnemonicData{"ORA (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0x11, MnemonicData{"ORA (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0x69, MnemonicData{"ADC #${}", AddressingMode::IMM, 1}},
            {0x6D, MnemonicData{"ADC ${}", AddressingMode::ABS, 2}},
            {0x7D, MnemonicData{"ADC ${},X", AddressingMode::X_IN_ABS, 2}},
            {0x79, MnemonicData{"ADC ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0x65, MnemonicData{"ADC ${}", AddressingMode::ZP, 1}},
            {0x75, MnemonicData{"ADC ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x61, MnemonicData{"ADC (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0x71, MnemonicData{"ADC (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0xC9, MnemonicData{"CMP #${}", AddressingMode::IMM, 1}},
            {0xCD, MnemonicData{"CMP ${}", AddressingMode::ABS, 2}},
            {0xDD, MnemonicData{"CMP ${},X", AddressingMode::X_IN_ABS, 2}},
            {0xD9, MnemonicData{"CMP ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0xC5, MnemonicData{"CMP ${}", AddressingMode::ZP, 1}},
            {0xD5, MnemonicData{"CMP ${},X", AddressingMode::X_IN_ZP, 1}},
            {0xC1, MnemonicData{"CMP (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0xD1, MnemonicData{"CMP (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0xE0, MnemonicData{"CPX #${}", AddressingMode::IMM, 1}},
            {0xEC, MnemonicData{"CPX ${}", AddressingMode::ABS, 2}},
            {0xE4, MnemonicData{"CPX ${}", AddressingMode::ZP, 1}},
            {0xC0, MnemonicData{"CPY #${}", AddressingMode::IMM, 1}},
            {0xCC, MnemonicData{"CPY ${}", AddressingMode::ABS, 2}},
            {0xC4, MnemonicData{"CPY ${}", AddressingMode::ZP, 1}},
            {0xE9, MnemonicData{"SBC #${}", AddressingMode::IMM, 1}},
            {0xED, MnemonicData{"SBC ${}", AddressingMode::ABS, 2}},
            {0xFD, MnemonicData{"SBC ${},X", AddressingMode::X_IN_ABS, 2}},
            {0xF9, MnemonicData{"SBC ${},Y", AddressingMode::Y_IN_ABS, 2}},
            {0xE5, MnemonicData{"SBC ${}", AddressingMode::ZP, 1}},
            {0xF5, MnemonicData{"SBC ${},X", AddressingMode::X_IN_ZP, 1}},
            {0xE1, MnemonicData{"SBC (${},X)", AddressingMode::X_IN_ZP_IND, 1}},
            {0xF1, MnemonicData{"SBC (${}),Y", AddressingMode::ZP_IND_Y_IN, 1}},
            {0xCE, MnemonicData{"DEC ${}", AddressingMode::ABS, 2}},
            {0xDE, MnemonicData{"DEC ${},X", AddressingMode::X_IN_ABS, 2}},
            {0xC6, MnemonicData{"DEC ${}", AddressingMode::ZP, 1}},
            {0xD6, MnemonicData{"DEC ${},X", AddressingMode::X_IN_ZP, 1}},
            {0xEE, MnemonicData{"INC ${}", AddressingMode::ABS, 2}},
            {0xFE, MnemonicData{"INC ${},X", AddressingMode::X_IN_ABS, 2}},
            {0xE6, MnemonicData{"INC ${}", AddressingMode::ZP, 1}},
            {0xF6, MnemonicData{"INC ${},X", AddressingMode::X_IN_ZP, 1}},
            {0x4C, MnemonicData{"JMP ${}", AddressingMode::ABS, 2}},
            {0x6C, MnemonicData{"JMP (${})", AddressingMode::ABS_IND, 2}},
            {0x20, MnemonicData{"JSR ${}", AddressingMode::ABS, 2}},
            {0x90, MnemonicData{"BCC ${}", AddressingMode::REL, 1}},
            {0xB0, MnemonicData{"BCS ${}", AddressingMode::REL, 1}},
            {0xF0, MnemonicData{"BEQ ${}", AddressingMode::REL, 1}},
            {0x30, MnemonicData{"BMI ${}", AddressingMode::REL, 1}},
            {0xD0, MnemonicData{"BNE ${}", AddressingMode::REL, 1}},
            {0x10, MnemonicData{"BPL ${}", AddressingMode::REL, 1}},
            {0x50, MnemonicData{"BVC ${}", AddressingMode::REL, 1}},
            {0x70, MnemonicData{"BVS ${}", AddressingMode::REL, 1}},
    };
}

MnemonicData OpcodeTable::find(uint8_t opcode) const {
    auto found =  mOpcodeToMnemonicList.find(opcode);

    if (found != mOpcodeToMnemonicList.end())
        return mOpcodeToMnemonicList.find(opcode)->second;

    return {"UNDEFINED", AddressingMode::REL, 1};
}
